### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by zsiti4** [viktak/ha-cc-abalin-nameday#11]
Szia

Ez a kis hasznos kiegészités már nem akar müködni egy ideje a HA 2025.1.0 alatt meg tudnád javitani?

**Comment by viktak** [comment]
As I don't have the time to fix it (the upstream component has changed) AND is also obsolete, I will not update this sensor in the near future. However, you can use the solution (using a REST sensor) I suggested in another bug like this:
```yaml
- authentication: basic
  scan_interval: 3600
  resource: https://nameday.abalin.net/api/V2/today?timezone=Europe/Athens
  sensor:
    - name: "Nameday - HU"
      value_template: "{{ value_json.data.hu }}"

    - name: "Nameday - GR"
      value_template: "{{ value_json.data.gr }}"
```
